# Generated by Django 5.0.1 on 2024-02-15 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_comment_to_photo_alter_like_to_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_time_of_publication',)},
        ),
    ]
